# Generated by Django 4.2.2 on 2023-09-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('topics', models.TextField(default='', null=True)),
                ('selected_category', models.CharField(max_length=32, null=True)),
            ],
        ),
    ]
