# Generated by Django 4.2.2 on 2023-06-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_content_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='keywords',
            field=models.TextField(default=''),
        ),
    ]
