# Generated by Django 4.2.2 on 2023-10-02 05:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="content",
            name="selected_category",
        ),
    ]
