# Generated by Django 4.2.2 on 2023-06-22 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_content_keywords'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='keywords',
            new_name='topics',
        ),
    ]
