# Generated by Django 4.2.2 on 2023-10-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_remove_content_selected_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="question",
            field=models.TextField(default=""),
        ),
    ]
