# Generated by Django 4.2.2 on 2023-06-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_keywords_content_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='category',
            field=models.CharField(default='', max_length=20),
        ),
    ]
