# Generated by Django 4.2.2 on 2023-07-16 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_usercategory_alter_user_user_id_delete_userkeywords_and_more'),
        ('main', '0005_content_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='category',
        ),
        migrations.RemoveField(
            model_name='content',
            name='userName',
        ),
        migrations.AddField(
            model_name='content',
            name='inserted_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.usercategory'),
        ),
        migrations.AddField(
            model_name='content',
            name='selected_category',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user'),
        ),
        migrations.AlterField(
            model_name='content',
            name='topics',
            field=models.TextField(default='', null=True),
        ),
    ]
