# Generated by Django 4.2.2 on 2023-09-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='nickname',
            field=models.CharField(default='test_user', max_length=30),
        ),
    ]
