# Generated by Django 4.2.2 on 2023-07-16 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_password_alter_user_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userCategory_id', models.IntegerField()),
                ('inserted_category', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='hwid', max_length=32, null=True),
        ),
        migrations.DeleteModel(
            name='UserKeywords',
        ),
        migrations.AddField(
            model_name='usercategory',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user'),
        ),
    ]
