# Generated by Django 4.2.2 on 2023-10-07 05:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_remove_usercategory_usercategory_id"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Users",
        ),
    ]
